//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_BookStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int PaymentID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string PaymentType { get; set; }
        public string PaymentInvoice { get; set; }
        public Nullable<decimal> Currency { get; set; }
        public Nullable<System.DateTime> paymentDate { get; set; }
        public Nullable<int> CardID { get; set; }
        public Nullable<int> TransactionID { get; set; }
    }
}
